### PR TITLE
Refactoring of Library

### LINKED ISSUE #4: support interfaces
Like in the server plugin, interfaces can be used to represent labels that are applied to multiple types

like Person to Director and Actor.

- No CRUD operations for the interface? Or only updates / deletes but not CREATE
- Query methods for interfaces
- add label to nodes during concrete create (like createActor)

### LINKED ISSUE #17: add support for schema in TCK files
currently it's externally provided,
change that to use the schema in the markdown file

### LINKED ISSUE #37: parameters for skip / limit
Currently skip and limit are passed as literals to the generated cypher query
We want them to become parameters too

### LINKED ISSUE #43: Support for single object results
The information about whether to return an object or a list of objects must be provided by this library.

### PR DESCRIPTION
**Pull request by Andy2003**
This PR includes the following changes:

* Extraction of TypeHandler per method (create, update, merge, delete, query) for better code encapsulation
* Moving parsing code into constructor of handler to not run it on every query
* moving all tests into Ascii-Doc (resolves #17)
* structuring tests to provide a table of content (toc), also serves as an example (linked from readme.adoc)
* moving augementation tests into Ascii-Doc as well
* allow each test to be run individually by utilizing Junit 5 dynamic tests
* add support for nativeId (the neo4j internal ID)
* add support for CRUD on  relation types
* add support for dynamic properties (compatible with [neo4j-ogm-driver](https://github.com/neo4j/neo4j-ogm/blob/master/core/src/main/java/org/neo4j/ogm/annotation/Properties.java))
* add support for interfaces (resolves #4)
* fix of results not beeing a list (resolves #43)
* add support for parameters for skip / limit (resolves #37)
* add hook to use for permission checking (see [the tests](https://github.com/Andy2003/neo4j-graphql-java/blob/object-oriented/src/test/resources/object-filter-tests.adoc))

I know it's not quite common to put so many changes into one PR, but these are my ongoing library adjustments that I'd like to share.

### CODE REVIEW

**Comment by jexp** [comment]
Hi Andy,

thanks a lot for your PR. 
As we both are in Dresden, do you want to meet and go through it in person?

**Comment by jexp** [comment]
I think we can split the PR up into some smaller ones for the different topics and then handle them one by one.

**Comment by Andy2003** [comment]
> Hi Andy,
> 
> thanks a lot for your PR.
> As we both are in Dresden, do you want to meet and go through it in person?

Sure but I'm on vacation until mid of August

> I think we can split the PR up into some smaller ones for the different topics and then handle them one by one.

Sure, but at the end we have to go through https://github.com/neo4j-graphql/neo4j-graphql-java/pull/44/commits/4ca6b30b7c136f8f859c80862198ec4ea0d4b1cb which is massive. So I can combine some of the commits into separate PRs after my vacations. But some of the in-between-changes will get obsolete by the final state of this PR.

**Comment by jexp** [comment]
For the tck files, we wanted to stick with markdown as we plan to use them across neo4j-graphql-js too. And possibly for docs on grandstack.io

**Comment by Andy2003** [comment]
done in smaller PRs

**Pull request closed without merging**
