### PR TITLE
Resolve field alias in Cypher only if no DataFetchingInterceptor is used

### LINKED ISSUE #267: Field aliasing does not work if using DataFetchingInterceptor
**Describe the bug**

If using `DataFetchingInterceptor` field aliasing does not work, `null` is always returned and it does not matter whether the aliased type was a scalar or a complex type.

**Test Case**

***GraphQL schema***

```
type Movie {
  title: String
}
type Query {
  movie: [Movie]
}
```

***GraphQL request***

```
query {
  movie {
    someAlias: title
  }
}
```

***Expected cypher query***

since `graphql-java` is handling aliasing the cypher should look like this:

```
MATCH (movie:Movie)
RETURN movie {
	.title
} AS movie
```

instead it looks like this:

```
MATCH (movie:Movie)
RETURN movie {
	someAlias: movie.title
} AS movie
```

***Expected cypher params***

```
```

***Neo4j test data***

```
```

***Expected GraphQL response***

```
{
	"errors": [],
	"data": {
		"movie": [
			{
				"someAlias": "value representing the title"
			}
		]
	},
	"extensions": null,
	"dataPresent": true
}
```

**Additional context**

If using `Translator` this works fine because you get the cypher already with alias and you just run it and return the data as it was fetched by the cypher. If using `DataFetchingInterceptor` the cypher still contains the alias so the fetched data looks god at first sight, but when returned from the `DataFetchingInterceptor` `graphql-java` does a mapping using the type definition to return with the information about aliasing used in the request query. So it completely ignores the `someAlias` data in the result because it is not part of the type definition and instead it looks for `title` which it expects in the result (since it is not there `null` is returned) to later alias it with `someAlias` by itself.

Note that aliasing on query level works fine because you just fetch the data from neo4j using the `variable` (which can be an alias) but then return just the data from the `DataFetchingInterceptor` without the `variable` (without the alias) and aliasing is handled by `graphql-java` again and this time correctly of course.

So while fixing that take into account that the `Translator` approach might get broken.

### PR DESCRIPTION
**Pull request by Andy2003**
resolves #267

### CODE REVIEW

**Comment by Andy2003** [comment]
@Krejtcha can you please check this PR if it solves your issue correctly?

**Comment by Krejtcha** [comment]
@Andy2003 thank you for the fix, but unfortunately it fixes the problem only partially. Now aliases on fields work, but the main purpose of why aliases are used does not work. I did not have time to investigate the issues in detail so I do not know the cause. I can only provide you with this info:

- if you query for the same neo4j property multiple times and present a different alias it works fine: e.g. `aaa: identifier`, `bbb: identifier`
- if you query for the same "special" property like `_id` or ap property driven by `@cypher` directive e.g. `aaa: _id`, `bbb: _id` the library does not even come to the part where it tries to fetch data from neo4j and you will get a `DataFetchingException`: `Exception while fetching data (/someNode) : Duplicate key '_id'`
- the same happens if you query for the same relationship multiple times e.g. `aaa: RELATIONSHIP_TO_OtherNode (<some filter>) ...`, `bbb: RELATIONSHIP_TO_OtherNode (<some other filter>) ...` you will get a `DataFetchingException`: `Exception while fetching data (/someNode) : Duplicate key 'RELATIONSHIP_TO_OtherNode'` - this is the use case why aliases are needed because you can not do that without them - so this needs to work.

Hopefully this feedback will be helpful for you and you will be able to fix this issue.

**Comment by Andy2003** [comment]
@Krejtcha thank you for your feedback! I now had to implement a completely different approach. Please check again if the PR fixes your issue correctly now.

**Comment by Krejtcha** [comment]
@Andy2003 unfortunately is still does not work:

If there is a `@cypher` based property e.g. `_label: String!` defined as not null and I query:

```
	other {
                _label
		l: _label
	}
```

it is OK, but when I query just this:

```
	other {
		l: _label
	}
```

I get `NullValueInNonNullableField`: `The field at path '/other[0]/l' was declared as a non null type, but the code involved in retrieving data has wrongly returned a null value.  The graphql specification requires that the parent field be set to null, or if that is non nullable that it bubble up null to its parent and so on. The non-nullable type is 'String' within parent type 'Other'`

It behaves the same for `@relation` based properties and will probably behave the same for standard properties as well.

If I have a rich relationship and I identify the `from` node as `_start` and `to` node as `_end` and query the following:

```
	other {
		Test_RELATED_TO {
			_start {
				identifier
			}
			s: _start {
				identifier
			}
		}
	}
```

it works, but when query just this:

```
	other {
		Test_RELATED_TO {
			s: _start {
				identifier
			}
		}
	}
```

`s` is null.

If I query this:

```
	other {
		Test_RELATED_TO (_id: 48389) {
			_id
			_start {
				identifier
			}
		}
		r1: Test_RELATED_TO (_id: 0) {
			_id
			_start {
				identifier
			}
		}
	}
```

both `_id` for `r1` and for not aliased are the same: `48389` and if I query this:

```
	other {
		r1: Test_RELATED_TO (_id: 0) {
			_id
			_start {
				identifier
			}
		}
	}
```

again the error with `NullValueInNonNullableField` sicnce `Test_RELATED_TO` is defined as `[Test_RELATED_TO_Other!]!`

**Comment by Andy2003** [comment]
@Krejtcha I cant reproduce your described behavior, can you do me a favor and adjust https://github.com/neo4j-graphql/neo4j-graphql-java/pull/270/files#diff-39e36965c8869d32dea7d00ef257118ec05f65fac67eb0a4af6fd9e926de64b0 to represent your descibed behavior.

Could it be that you are stumbling over another issue: https://github.com/neo4j-graphql/neo4j-graphql-java/issues/87?

**Comment by Andy2003** [comment]
I moved the logic to `registerDataFetcher`, so your approach should work now.
In the examples we do the same as you:

https://github.com/neo4j-graphql/neo4j-graphql-java/blob/689ded127c117bd559f425436be05cfbcc6616c7/examples/dgs-spring-boot/src/main/kotlin/org/neo4j/graphql/examples/dgsspringboot/config/GraphQLConfiguration.kt#L52-L56

We could add some customizer callbacks (a.k.a. extension points) as a new feature. Feel free to create a feature request. PR's are of course always welcome as well!

**Pull request merged**
